[package]
name = "grk-rs-trial"
version = "0.1.0"
authors = ["cohyou"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
gio = "0.9.1"